export const env = {
  APP_URL: process.env.APP_URL ?? '',
  APPWRITE_ENDPOINT: process.env.APPWRITE_ENDPOINT ?? '',
  APPWRITE_PROJECT_ID: process.env.APPWRITE_PROJECT_ID ?? '',
  APPWRITE_FUNCTION_MINDMAP_NODES: process.env.APPWRITE_FUNCTION_MINDMAP_NODES ?? '',
  APPWRITE_FUNCTION_MINDMAP_EDGES: process.env.APPWRITE_FUNCTION_MINDMAP_EDGES ?? '',
}
