export const env = {
  APPWRITE_ENDPOINT: process.env.APPWRITE_ENDPOINT ?? '',
  APPWRITE_PROJECT_ID: process.env.APPWRITE_PROJECT_ID ?? '',
  APPWRITE_FUNCTION_MINDMAP: process.env.APPWRITE_FUNCTION_MINDMAP ?? '',
}
